const GAME_CONFIG = {
    INITIAL_HEALTH: 100,
    INITIAL_MONEY: 0,
    INITIAL_FOOD: 0,
    MAX_HEALTH: 100,
    SLEEP_HEALTH_INCREASE: 30,
    EAT_HEALTH_INCREASE: 10,
    BREAD_COST: 5,
    BREAD_FOOD_INCREASE: 1,
    MEAT_COST: 10,
    MEAT_FOOD_INCREASE: 2,
    WORK_HEALTH_DECREASE: 1,
    WORK_MONEY_INCREASE: 1,
    EAT_FOOD_DECREASE: 1,
   }
export default GAME_CONFIG;